site_name: WordPress Playground
theme:
    name: readthedocs

repo_url: https://github.com/WordPress/wordpress-playground
edit_uri: blob/trunk/docs/

nav:
    - Overview: index.md
    - WordPress in the browser: using-wordpress-in-the-browser.md
    - PHP in the browser: using-php-in-the-browser.md
    - PHP in Javascript: using-php-in-javascript.md
    - API Reference:
          - php-wasm Reference: api/php-wasm.md
          - php-wasm-browser Reference: api/php-wasm-browser.md
          - wordpress-playground Reference: api/wordpress-playground.md

# markdown_extensions:
#     - meta
#     - toc

hooks: ['docs_hooks.py']
