packages:
    # all packages in direct subdirs of packages/
    # - 'packages/**'
    - 'packages/php-wasm/*'
    # - 'dist/packages/playground/**'
    # exclude packages that are inside test directories
    - '!**/test/**'
