name: Clone the repository, install dependencies, and configures nx variables

runs:
    using: 'composite'
    steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/prepare-playground
        - name: Install Playwright Browsers
          run: sudo npx playwright install --with-deps
        - name: Prepare app deploy and offline mode
          run: npx nx run playground-website:e2e:playwright:prepare-app-deploy-and-offline-mode
        - name: Zip dist
          run: zip -r dist.zip dist
        - name: Upload dist
          uses: actions/upload-artifact@v4
          with:
              name: playwright-dist
              path: dist.zip
