name: Deploy to playground.wordpress.net

on:
    workflow_dispatch:
    # Deploy the website every day at 9am and 6pm UTC
    # TODO: Re-enable this before merge
    #schedule:
    #    - cron: '0 9,18 * * *'

    # TODO: Remove this before merging
    pull_request:

concurrency:
    group: website-deployment
    # TODO: Enable cancel-in-progress once we are deploying per commit?
    #cancel-in-progress: true

jobs:
    build_and_deploy:
        # Only run this workflow from the trunk branch and when it's triggered by another workflow OR dmsnell OR adamziel
        #TODO: Re-enable this check before merging
        #if: >
        #github.ref == 'refs/heads/trunk' && (
        #    github.event_name == 'workflow_run' ||
        #    github.event_name == 'workflow_dispatch' ||
        #    github.actor == 'adamziel' ||
        #    github.actor == 'dmsnell' ||
        #    github.actor == 'bgrgicak' ||
        #    github.actor == 'brandonpayton'
        #)

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        environment:
            name: playground-wordpress-net
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - run: npm run build

            # TODO: Target production site before merging
            - name: Deploy to playground.wordpress.net
              shell: bash
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.DEPLOY_WEBSITE_TARGET_HOST_KEY }}" >> ~/.ssh/known_hosts
                  echo "${{ secrets.DEPLOY_WEBSITE_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 0600 ~/.ssh/*

                  # Website files
                  rsync -avz -e "ssh -i ~/.ssh/id_ed25519" --delete \
                    dist/packages/artifacts/wasm-wordpress-net/ \
                    ${{ secrets.STAGING_WEBSITE_TARGET_USER }}@${{ secrets.STAGING_WEBSITE_TARGET_HOST }}:'~/updated-playground-files'

                  # Host-specific deployment scripts and server config
                  rsync -avz -e "ssh -i ~/.ssh/id_ed25519" --delete \
                    packages/playground/website-deployment/ \
                    ${{ secrets.STAGING_WEBSITE_TARGET_USER }}@${{ secrets.STAGING_WEBSITE_TARGET_HOST }}:'~/website-deployment'

                  # Copy MIME types for use with PHP-served files
                  scp -i ~/.ssh/id_ed25519 \
                    packages/php-wasm/universal/src/lib/mime-types.json \
                    ${{ secrets.STAGING_WEBSITE_TARGET_USER }}@${{ secrets.STAGING_WEBSITE_TARGET_HOST }}:'~/website-deployment/'

                  # Apply update
                  ssh -i ~/.ssh/id_ed25519 \
                    ${{ secrets.STAGING_WEBSITE_TARGET_USER }}@${{ secrets.STAGING_WEBSITE_TARGET_HOST }} \
                    -tt -C '~/website-deployment/apply-update.sh'
