name: CI
on:
    push:
        branches:
            - trunk
    pull_request:

jobs:
    # This step:
    # * Warms up the node_modules cache
    # * Performs linting and typechecking
    #
    # The linting tasks take ~5s to complete and it doesn't
    # make sense to separate them into separate steps that would
    # take ~25s just to run git clone and restore node_modules.
    lint-and-typecheck:
        name: 'Lint and typecheck'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=lint
            - run: npx nx affected --target=typecheck
    test:
        runs-on: ubuntu-latest
        needs: [lint-and-typecheck]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=test --configuration=ci
    build:
        runs-on: ubuntu-latest
        needs: [lint-and-typecheck]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=build --parallel=3
            # Experimental: Deploy the docs
            - uses: actions/upload-pages-artifact
              with:
                  artifact-name: github-pages
                  path: dist/docs/build

    # Deploy job
    deploy:
        # Add a dependency to the build job
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
