name: CI
on:
    push:
        branches:
            - trunk
    pull_request:

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/prepare-playground
            - run: npx nx format:check || npx prettier --check .
            - run: npx nx affected --target=lint
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=typecheck
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=test --configuration=ci
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/prepare-playground
            - run: npx nx affected --target=build --parallel=3
