name: CI
on:
    push:
        branches:
            - trunk
    pull_request:

jobs:
	# Use just this CI step to speed repro of mem OOB error
    test-unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - run: node --expose-gc node_modules/nx/bin/nx affected --target=test --configuration=ci
