name: Continue deploying to playground.wordpress.net (don't use manually)
# Sorry, the previous job just built it and uploaded it to GitHub

on:
    workflow_run:
        workflows: [Deploy to playground.wordpress.net]
        types:
            - completed

    # TODO: Remove once done with testing
    pull_request:

jobs:
    build_and_deploy:
        # Only run this workflow from the trunk branch and when it's triggered by another workflow OR dmsnell OR adamziel
        if: >
            github.ref == 'refs/heads/trunk' && (
                github.event.workflow_run.conclusion == 'success' ||
                github.actor == 'adamziel' ||
                github.actor == 'dmsnell' ||
                github.actor == 'bgrgicak' ||
                github.actor == 'brandonpayton'
            )

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        environment:
            name: playground-wordpress-net
        steps:
            - name: Wait for latest build artifact
              shell: bash
              # Sleep to give the GitHub API time to register the artifact,
              # otherwise the artifact will not be available when the webhook is called
              run: |
                  while true; do
                      API_HASH=$(curl 'https://api.github.com/repos/wordpress/wordpress-playground/actions/artifacts?name=playground-website&per_page=2' \
                          | jq -r '.artifacts[0].workflow_run.head_sha')
                      if [ "$API_HASH" = "$GITHUB_SHA" ]; then
                          break;
                      fi;
                      echo "$API_HASH was not $GITHUB_SHA, waiting 10 seconds...";
                      sleep 10;
                  done;
            - uses: actions/download-artifact@v2
              with:
                  name: playground-website
                  path: playground-website
            - name: Deploy to playground.wordpress.net
              run: |
                  echo "$DEPLOY_WEBSITE_TARGET_HOST_KEY" >> ~/.ssh/known_hosts
                  echo "$DEPLOY_WEBSITE_PRIVATE_KEY" > ~/.ssh/id_ed25519
                  rsync -avz -e "ssh -i ~/.ssh/id_ed25519" playground-website/ $DEPLOY_WEBSITE_TARGET_USER@$DEPLOY_WEBSITE_TARGET_HOST:/srv/htdocs/playground-files

            # TODO in subsequent PR: Copy latest custom-redirects.php from git
            # TODO in subsequent PR: Copy latest purge cache script from website file and run it
