name: GitHub Board Automation

on:
    workflow_dispatch:
    # Run every 10 minutes
    schedule:
        - cron: '*/10 * * * *'

jobs:
    run-php-in-docker:
        runs-on: ubuntu-latest
        environment:
            name: project-board-automation

        steps:
            - name: Sparse checkout packages/meta/
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1
                  sparse-checkout: 'packages/meta/'

            - name: Run PHP script in Docker container
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  docker run --rm \
                    -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                    -v ${{ github.workspace }}:/workspace \
                    -w /workspace \
                    php:8.0-cli php packages/meta/bin/project_board_automation.php
