name: 'Refresh WordPress assets'

on:
    workflow_dispatch:

jobs:
    build_and_deploy:
        # Only run this workflow from the trunk branch
        if: github.ref == 'refs/heads/trunk'
        runs-on: ubuntu-latest
        environment:
            name: wordpress-assets
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/prepare-playground
            - name: 'Recompile WordPress'
              shell: bash
              run: npx nx recompile-wordpress:all playground-remote
            - name: Config git user
              run: |
                  git config --global user.name "deployment_bot"
                  git config --global user.email "deployment_bot@users.noreply.github.com"
                  git remote set-url origin https://${{ secrets.GH_ACTOR }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
                  git add -A
                  git commit -a -m "Recompile WordPress"
                  git push origin HEAD:trunk
